[build]
  publish = "dist"
  command = "npm run build"
[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
# /studio -> Sanity host
[[redirects]]
  from = "/studio"
  to   = "https://diyetsiten.sanity.studio"
  status = 301

[[redirects]]
  from = "/studio/*"
  to   = "https://diyetsiten.sanity.studio/:splat"
  status = 200